Allow null timestamp values
mikkopaderes/ember-cloud-firestore-adapter pull request #133
Opened 2020-11-19 23:08 UTC by charlesfries

2020-11-20 05:31 UTC, mikkopaderes requested changes
Thanks for this. I understand the use-case and yeah, we should support it. But we also need to update the docs and unit tests to cover this new feature. Would you mind changing it as well? Should be a quick one 😄

2020-11-20 05:31 UTC, mikkopaderes commented on addon/transforms/timestamp.js
> +    if (typeOf(deserialized) !== 'date' && typeOf(deserialized) !== 'null') {
Should this be `null` instead of `'null'`? `'null'` would end up being a string, right?

2020-11-20 05:38 UTC, mikkopaderes commented on addon/transforms/timestamp.js
> +    if (typeOf(deserialized) !== 'date' && typeOf(deserialized) !== 'null') {
Nevermind, I didn't notice you're doing a `typeOf` here. Making it `deserialized !== null` should work as well and is more straightforward.

2020-11-20 17:29 UTC, charlesfries commented
Yes, I'll get on it later tonight 👍

2020-12-09 03:30 UTC, charlesfries commented
Finally got around to this. Seems like there are some conflicts however. But I updated tests and wrote some more documentation 👌🏻

2020-12-09 15:44 UTC, mikkopaderes commented
> 
> 
> Finally got around to this. Seems like there are some conflicts however. But I updated tests and wrote some more documentation 👌🏻

Yes, thanks. The conflict is because the files you're editing are now on TypeScript.

2020-12-09 18:15 UTC, charlesfries commented
Ah I see. Just pushed another commit to update the files to TS.

Also lmk if the documentation is too verbose, I tried to show all three use cases for the transform

2020-12-10 15:27 UTC, mikkopaderes requested changes
There's an existing test that's failing because it was using the `null` value and expecting a Firestore timestamp. Would it be okay for you to change that as well? :smile:

2020-12-10 15:27 UTC, mikkopaderes commented on docs/transforms.md
> +  @attr('timestamp', { defaultValue: null }) publishOn;
These are docs that I feel that we don't need. It should be covered by Ember Data itself.

2020-12-10 15:27 UTC, mikkopaderes commented on docs/transforms.md
> +```
Just like you mentioned, I feel that the docs makes things too verbose. Your [line 18](https://github.com/mikkopaderes/ember-cloud-firestore-adapter/pull/133/files#diff-b7cdfd453c5a6d190f2c990a55cf8439815dc9ac1bb1e0a94b362110370d2dd6R18) I believe should be enough to cover things in a simple manner.

2021-01-09 06:56 UTC, mikkopaderes commented
Thinking about this feature more, I think I may have jumped a bit to early on agreeing that we should support this.

Right now, I can't imagine any generic use-case for this and it may just add confusion to the `Timestamp` transform on why it's allowed to be `null`. If anyone needs this, I'd recommend to create your own custom transform for your application called `nullable-timestamp`.

Thank you for taking time on working on this PR and I'm sorry as well if this seems like lost time on your side. 😢

2021-01-09 06:56 UTC, closed without merging