Uninstall `ember-classic-decorator`
mikkopaderes/ember-cloud-firestore-adapter pull request #215
Opened 2021-12-22 19:18 UTC by charlesfries

`ember-classic-decorator` in its current state is not compatible with Ember 4 (the following PR will fix it but it's yet to be merged: https://github.com/emberjs/ember-classic-decorator/pull/83)

I think we are able to get by without it, but I'm going to do some research into Ember Data and Ember Simple Auth to make sure. Opening the PR anyways.

2021-12-22 19:21 UTC, charlesfries commented on addon/adapters/cloud-firestore-modular.ts
> +  public constructor(...args: any[]) {
Tried using the `unknown[]` type here but I can't then call `super()` with that unknown type.

2021-12-23 03:57 UTC, mikkopaderes commented
I can recall now why I used `ember-classic-decorator`, it's because if we use the `init` hook, the eslint will throw [this](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/classic-decorator-hooks.md) error

2021-12-23 04:11 UTC, mikkopaderes approved these changes

2021-12-23 04:34 UTC, mikkopaderes requested changes
Let me hold off on this change. I'm applying it in #217 as I want to fix all deprecations in 1 PR so that we could see if the CI build succeeds.

2021-12-23 06:09 UTC, mikkopaderes commented
@charlesfries I've applied this in #217. Thanks for providing the fix!

2021-12-23 06:10 UTC, closed without merging